# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SCRMap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SCRMap

  target 'SCRMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SCRMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'BaiduMapKit', '~> 3.4.2'
 pod 'MJExtension', '~> 3.0.13'
pod 'Masonry'
end
